class MESSAGE:
    SUCCESS = "SUCCESS"
    UNKNOWN_SEVER_ERROR = "UNKNOWN_SEVER_ERROR"
    INVALID_FORMAT = "INVALID_FORMAT"
    AUTH_REQUIRED = "AUTH_REQUIRED"

    # users
    EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE"
    NICKNAME_ALREADY_IN_USE = "NICKNAME_ALREADY_IN_USE"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH"


class TOKEN:
    ACCESS_EXPIRE_TIME = 3600
    REFRESH_EXPIRE_TIME = 86400
