class CODE:
    SUCCESS = (0, "SUCCESS")
    UNKNOWN_SEVER_ERROR = (1, "UNKNOWN_SEVER_ERROR")
    INVALID_PARAMETERS = (2, "INVALID_PARAMETERS")
    AUTH_REQUIRED = (3, "AUTH_REQUIRED")

    # users
    EMAIL_ALREADY_EXISTED = (100, "EMAIL_ALREADY_EXISTED")
    USER_NOT_FOUND = (101, "USER_NOT_FOUND")
    PASSWORD_MISMATCH = (102, "PASSWORD_MISMATCH")


class TOKEN:
    ACCESS_EXPIRE_TIME = 3600
    REFRESH_EXPIRE_TIME = 86400
